// ─── Enums ───────────────────────────────────────────────────────────────────

export enum UserRole {
  CANDIDATE = 'CANDIDATE',
  ADMIN = 'ADMIN',
}

export enum WorkMode {
  ONSITE = 'ONSITE',
  HYBRID = 'HYBRID',
  REMOTE = 'REMOTE',
}

export enum EmploymentType {
  FULL_TIME = 'FULL_TIME',
  PART_TIME = 'PART_TIME',
  CONTRACT = 'CONTRACT',
  FREELANCE = 'FREELANCE',
  INTERNSHIP = 'INTERNSHIP',
}

export enum SkillLevel {
  BEGINNER = 'BEGINNER',
  INTERMEDIATE = 'INTERMEDIATE',
  ADVANCED = 'ADVANCED',
  EXPERT = 'EXPERT',
}

export enum SkillGapLevel {
  STRONG = 'STRONG',
  PARTIAL = 'PARTIAL',
  MISSING = 'MISSING',
}

export enum SkillGapPriority {
  CRITICAL = 'CRITICAL',
  HIGH = 'HIGH',
  MEDIUM = 'MEDIUM',
  LOW = 'LOW',
}

export enum ApplicationState {
  DISCOVERED = 'DISCOVERED',
  ANALYZING = 'ANALYZING',
  MATCHED = 'MATCHED',
  QUALIFIED = 'QUALIFIED',
  RESUME_GENERATING = 'RESUME_GENERATING',
  RESUME_READY = 'RESUME_READY',
  ATS_VALIDATING = 'ATS_VALIDATING',
  APPLICATION_READY = 'APPLICATION_READY',
  AWAITING_USER = 'AWAITING_USER',
  APPLICATION_STARTED = 'APPLICATION_STARTED',
  FORM_MAPPING = 'FORM_MAPPING',
  FORM_FILLING = 'FORM_FILLING',
  QUESTIONS_COMPLETED = 'QUESTIONS_COMPLETED',
  SUBMITTING = 'SUBMITTING',
  SUBMITTED = 'SUBMITTED',
  TRACKING = 'TRACKING',
  // Exception states
  CAPTCHA_REQUIRED = 'CAPTCHA_REQUIRED',
  LOGIN_REQUIRED = 'LOGIN_REQUIRED',
  USER_ACTION_REQUIRED = 'USER_ACTION_REQUIRED',
  JOB_CLOSED = 'JOB_CLOSED',
  DUPLICATE_APPLICATION = 'DUPLICATE_APPLICATION',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  APPLICATION_ERROR = 'APPLICATION_ERROR',
  PLATFORM_ERROR = 'PLATFORM_ERROR',
  NETWORK_ERROR = 'NETWORK_ERROR',
}

export enum ApplyMode {
  MANUAL = 'MANUAL',
  ASSISTED = 'ASSISTED',
  AUTO = 'AUTO',
}

export enum ResumeType {
  MASTER = 'MASTER',
  BASE = 'BASE',
  ROLE = 'ROLE',
  TAILORED = 'TAILORED',
}

export enum EvidenceStatus {
  PENDING = 'PENDING',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
}

export enum EvidenceSource {
  RESUME = 'RESUME',
  MANUAL = 'MANUAL',
  CERTIFICATION = 'CERTIFICATION',
  PROJECT = 'PROJECT',
  WORK_HISTORY = 'WORK_HISTORY',
}

export enum AIProvider {
  NONE = 'none',
  OLLAMA = 'ollama',
  GEMINI = 'gemini',
  OPENAI = 'openai',
}

export enum ConnectorCapability {
  COMPANY_SEARCH = 'COMPANY_SEARCH',
  JOB_SEARCH = 'JOB_SEARCH',
  JOB_DETAILS = 'JOB_DETAILS',
  JD_CAPTURE = 'JD_CAPTURE',
  APPLICATION_PREPARATION = 'APPLICATION_PREPARATION',
  APPLICATION_FILL = 'APPLICATION_FILL',
  APPLICATION_SUBMISSION = 'APPLICATION_SUBMISSION',
  STATUS_TRACKING = 'STATUS_TRACKING',
}

export enum JobFreshness {
  LAST_24H = 'LAST_24H',
  LAST_3_DAYS = 'LAST_3_DAYS',
  LAST_7_DAYS = 'LAST_7_DAYS',
  LAST_30_DAYS = 'LAST_30_DAYS',
}

export enum ApplicationEventType {
  JOB_DISCOVERED = 'JOB_DISCOVERED',
  JD_CAPTURED = 'JD_CAPTURED',
  JD_ANALYZED = 'JD_ANALYZED',
  ROLE_MATCHED = 'ROLE_MATCHED',
  MATCH_SCORE_CALCULATED = 'MATCH_SCORE_CALCULATED',
  RESUME_GENERATION_STARTED = 'RESUME_GENERATION_STARTED',
  RESUME_GENERATED = 'RESUME_GENERATED',
  ATS_VALIDATION_COMPLETED = 'ATS_VALIDATION_COMPLETED',
  FACT_CHECK_COMPLETED = 'FACT_CHECK_COMPLETED',
  APPLICATION_READY = 'APPLICATION_READY',
  APPLICATION_STARTED = 'APPLICATION_STARTED',
  FORM_FIELDS_MAPPED = 'FORM_FIELDS_MAPPED',
  SUBMISSION_STARTED = 'SUBMISSION_STARTED',
  APPLICATION_SUBMITTED = 'APPLICATION_SUBMITTED',
  APPLICATION_FAILED = 'APPLICATION_FAILED',
  INTERVIEW_SCHEDULED = 'INTERVIEW_SCHEDULED',
  APPLICATION_REJECTED = 'APPLICATION_REJECTED',
  OFFER_RECEIVED = 'OFFER_RECEIVED',
}

export enum NotificationType {
  NEW_HIGH_MATCH_JOB = 'NEW_HIGH_MATCH_JOB',
  APPLICATION_READY = 'APPLICATION_READY',
  USER_ACTION_REQUIRED = 'USER_ACTION_REQUIRED',
  APPLICATION_SUBMITTED = 'APPLICATION_SUBMITTED',
  APPLICATION_ERROR = 'APPLICATION_ERROR',
  INTERVIEW_SCHEDULED = 'INTERVIEW_SCHEDULED',
  STATUS_CHANGED = 'STATUS_CHANGED',
  OFFER_RECEIVED = 'OFFER_RECEIVED',
}

export enum InterviewType {
  PHONE_SCREEN = 'PHONE_SCREEN',
  TECHNICAL = 'TECHNICAL',
  CODING = 'CODING',
  SYSTEM_DESIGN = 'SYSTEM_DESIGN',
  BEHAVIORAL = 'BEHAVIORAL',
  ONSITE = 'ONSITE',
  FINAL = 'FINAL',
}
